Repository andela/savage_rangers-ah, pull requests merged in 2019-07, with the labels that each got.

#44 [Ft 166240825] user's profile
  package.json
  src/api/controllers/articleController.js
  src/api/controllers/profileController.js
  src/api/models/article.js
  src/api/models/category.js
  src/api/models/index.js
  src/api/models/user.js
  src/api/routes/index.js
  src/api/routes/profileRouter.js
  src/api/seeders/20190621184055-user.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  src/helpers/results/send.profile.js
  src/helpers/tests/signup.js
  src/middlewares/authenticate.js
  src/middlewares/validations/body.inputs.js
  tests/images/test.jpg
  tests/profile.test.js
Labels: Needs approval

#43 #[166240827] Users should be able to give a rating to an article
  src/api/controllers/articleController.js
  src/api/controllers/articleRatingController.js
  src/api/migrations/20190622195903-add-unique-constraint-article.js
  src/api/migrations/20200622165309-create-rating.js
  src/api/models/index.js
  src/api/models/rating.js
  src/api/routes/articleRouter.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  src/helpers/constants/numbers.js
  src/helpers/constants/validation.schemas.js
  src/helpers/slug.maker.js
  src/middlewares/checkExistingRating.js
  tests/rateArticle.test.js
  tests/updateArticle.test.js
Labels: Needs Merge, Needs approval

#59 #166647233 enable authors to delete their own articles
  src/api/controllers/articleController.js
  src/api/models/index.js
  src/api/routes/articleRouter.js
  src/api/routes/index.js
  src/api/seeders/20190621184055-user.js
  src/api/seeders/20190624184857-Article.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  src/middlewares/checkArticleOwnership.js
  tests/deleteArticle.test.js
Labels: Needs approval

#58 #166240828 Users should be able to fetch article's ratings
  .eslintignore
  package.json
  src/api/controllers/articleRatingController.js
  src/api/controllers/verifyEmail.js
  src/api/models/index.js
  src/api/models/rating.js
  src/api/models/user.js
  src/api/routes/articleRouter.js
  src/api/routes/password.reset.js
  src/api/routes/profileRouter.js
  src/api/seeders/20190624184857-Article.js
  src/api/seeders/20190624184859-test-ratings.js
  src/docs/swagger.json
  src/helpers/calculate.ratings.percentages.js
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  src/helpers/generate.pagination.details.js
  src/helpers/sequelize.initializer.js
  src/helpers/tokens/decode.token.js
  src/middlewares/ValidateUser.js
  src/middlewares/validations/body.inputs.js
  src/middlewares/validations/ratings.routes.js
  tests/article.ratings.js
Labels: Needs approval

#57 #166720098 Enable users to fetch articles
  package.json
  src/api/controllers/articleController.js
  src/api/models/article.js
  src/api/models/category.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190621184055-user.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  tests/articles.test.js
Labels: Needs approval

#62 #[166240841] Users should be able to report an article
  .eslintrc.json
  src/api/controllers/articleController.js
  src/api/migrations/20190625141142-create-reasons.js
  src/api/migrations/20190625141143-rename-column-name-reasons.js
  src/api/migrations/20190701163644-create-report.js
  src/api/models/index.js
  src/api/models/reasons.js
  src/api/models/report.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190703095400-reasons.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  tests/reportArticle.test.js
  tests/updateArticle.test.js
Labels: Needs Review

#50 #166240836 Enable user to get Authors
  package.json
  src/api/controllers/authorsController.js
  src/api/routes/authorsRoutes.js
  src/api/routes/index.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  tests/getAuthors.test.js
Labels: Needs approval

#65 #166240846 highlight text
  src/api/controllers/articleController.js
  src/api/migrations/20190703103749-create-highlight.js
  src/api/models/article.js
  src/api/models/highlight.js
  src/api/models/index.js
  src/api/models/user.js
  src/api/routes/articleRouter.js
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  tests/highlight.test.js
Labels: Needs approval

#49 #166240832 Enables the user to follow and unfollow
  package.json
  src/api/controllers/followingController.js
  src/api/controllers/verifyEmail.js
  src/api/migrations/20190706134036-create-following.js
  src/api/models/following.js
  src/api/models/index.js
  src/api/models/user.js
  src/api/routes/index.js
  src/api/routes/profileRouter.js
  src/api/seeders/20190621184055-user.js
  src/api/seeders/20190704143249-test-follow-data.js
  src/helpers/constants/error.messages.js
  tests/follow.test.js
  tests/verify.test.js
Labels: Needs approval

#68 #[166240839] Users should be able to share articles across different channels
  package.json
  src/api/controllers/articleController.js
  src/api/migrations/20190704140437-create-share.js
  src/api/models/index.js
  src/api/models/share.js
  src/api/routes/articleRouter.js
  src/configs/environments.js
  src/middlewares/shareArticle.js
  tests/socialShare.test.js
Labels: Needs Merge, Needs approval

#64 #166240844 Admin should be able to create, update and block/unblock user
  src/api/controllers/adminPermissionsController.js
  src/api/migrations/20190701173128-add-role.js
  src/api/models/user.js
  src/api/routes/adminRouter.js
  src/api/routes/index.js
  src/api/seeders/20190621184055-user.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  src/middlewares/IsAdmin.js
  src/middlewares/checkUser.js
  src/middlewares/isBlocked.js
  tests/admin.test.js
  tests/getAuthors.test.js
Labels: Needs Review, Needs approval

#74 166240830 Users should be able to comment on articles
  src/api/controllers/commentController.js
  src/api/migrations/20190703130611-create-comment-table.js
  src/api/models/article.js
  src/api/models/comment.js
  src/api/models/index.js
  src/api/models/user.js
  src/api/routes/articleRouter.js
  src/helpers/constants/error.messages.js
  src/helpers/constants/status.codes.js
  src/helpers/constants/validation.schemas.js
  src/middlewares/check.comment.ownership.js
  src/middlewares/get.comment.record.js
  src/middlewares/getOneArticle.js
  src/middlewares/validations/comment.update.delete.js
  src/middlewares/validations/get.comments.route.js
  tests/article.comments.js
  tests/rateArticle.test.js
  tests/updateArticle.test.js
Labels: Needs approval

#61 #166240840 Enables user to bookmark an article
  src/api/controllers/bookmarkController.js
  src/api/migrations/20190622195902-create-article.js
  src/api/migrations/20190701162027-create-bookmark.js
  src/api/models/article.js
  src/api/models/bookmark.js
  src/api/models/index.js
  src/api/models/user.js
  src/api/routes/bookmarkRouter.js
  src/api/routes/index.js
  src/api/seeders/20190621184055-user.js
  src/api/seeders/20190701190735-test-bookmarks.js
  src/helpers/constants/error.messages.js
  tests/bookmark.test.js
Labels: Needs Review, Needs approval

#71 #166979383 allow admin and moderator to block reported Articles
  src/api/controllers/adminPermissionsController.js
  src/api/controllers/articleController.js
  src/api/migrations/20190707124518-add-isBlocked.js
  src/api/models/article.js
  src/api/models/reasons.js
  src/api/models/report.js
  src/api/models/user.js
  src/api/routes/adminRouter.js
  src/api/routes/index.js
  src/api/seeders/20190621184055-user.js
  src/api/seeders/20190708175903-report.js
  src/helpers/constants/error.messages.js
  src/middlewares/CheckIfModerator.js
  src/middlewares/isArticleBlocked.js
  tests/admin.article.test.js
Labels: Needs Merge, Needs Review

#73 #167065031 Get article by category endpoint
  src/api/controllers/articleController.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190624184857-Article.js
  tests/article.js
Labels: Needs Merge

#63 #166240834 Users should be able to tag their articles
  package.json
  src/api/controllers/articleController.js
  src/api/controllers/articleTagController.js
  src/api/migrations/20190701093346-delete-tags-list-attribute.js
  src/api/migrations/20190701142751-create-tags-table.js
  src/api/migrations/20190703201320-create-ArticlesTags-table.js
  src/api/models/article.js
  src/api/models/articlesTags.js
  src/api/models/index.js
  src/api/models/tag.js
  src/api/models/user.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190624184857-Article.js
  src/api/seeders/20190701144805-test-tags.js
  src/api/seeders/20190715125427-create-admin.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  src/helpers/constants/status.codes.js
  src/helpers/constants/validation.schemas.js
  src/helpers/create.article.tags.js
  src/helpers/validators/articleValidator.js
  src/middlewares/check.incoming.tags.js
  src/middlewares/get.new.tags.js
  src/middlewares/validations/query.tags.table.route.js
  src/middlewares/validations/validate.existing.articles.tags.js
  tests/article.js
  tests/article.tags.test.js
  tests/articles.test.js
  tests/deleteArticle.test.js
  tests/getAuthors.test.js
  tests/updateArticle.test.js
Labels: Needs approval

#56 #166240837 search functionality
  src/api/controllers/articleController.js
  src/api/routes/article.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190701144805-test-tags.js
  src/helpers/constants/error.messages.js
  tests/article.search.test.js
Labels: Needs Merge

#70 # 166979413 Terms and condition endpoints
  src/api/controllers/termsAndConditionsController.js
  src/api/migrations/20190704181803-termsAndConditions.js
  src/api/models/index.js
  src/api/models/termsAndConditions.js
  src/api/routes/index.js
  src/api/routes/termsAndConditions.js
  src/api/seeders/20190704175121-terms-conditions.js
  tests/termsAndConditions.js
Labels: Needs approval

#54 166240838 Users should be able to see time it takes to read an article
  src/api/controllers/articleController.js
  src/api/migrations/20190716190526-add-readtime-column-on-article.js
  src/api/models/article.js
  src/api/seeders/20190624184857-Article.js
  src/helpers/read.time.estimator.js
  tests/read.time.estimator.test.js
Labels: Needs approval

#66 # 166240842 comment reaction like dislike
  src/api/controllers/commentReactionsController.js
  src/api/migrations/20190703212525-likeDislike.js
  src/api/migrations/20190717125234-reactions.js
  src/api/models/comment.js
  src/api/models/index.js
  src/api/models/reactions.js
  src/api/models/user.js
  src/api/routes/commentReactionsRoute.js
  src/api/routes/index.js
  src/api/seeders/20190704133048-comment.js
  src/middlewares/commentReaction.js
  tests/commentReactions.js
Labels: Needs approval

#72 #166240843 article's statistics
  src/api/controllers/articleController.js
  src/api/migrations/20190708141337-create-stat.js
  src/api/models/article.js
  src/api/models/index.js
  src/api/models/read.js
  src/api/models/user.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190709081740-test-stat.js
  src/api/seeders/20190709104313-test-share.js
  src/middlewares/optionalAuth.js
  tests/article.stat.test.js
Labels: Needs Merge

#78 #167289579 save article as draft
  Procfile
  package.json
  src/api/controllers/articleController.js
  src/api/migrations/20190622195902-create-article.js
  src/api/migrations/20190716072908-create-status.js
  src/api/models/article.js
  src/api/routes/articleRouter.js
  src/api/seeders/20190624184857-Article.js
  src/helpers/constants/error.messages.js
  src/helpers/validators/articleValidator.js
  tests/article.js
  tests/draft.test.js
  tests/getAuthors.test.js
Labels: Needs approval

#77 #[167284622] Users should be able to report inappropriate comment
  src/api/controllers/reportCommentController.js
  src/api/controllers/termsAndConditionsController.js
  src/api/migrations/20200622165311-create-commentReport-table.js
  src/api/models/index.js
  src/api/models/reasons.js
  src/api/models/reportComment.js
  src/api/routes/articleRouter.js
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  src/middlewares/getOneArticle.js
  tests/reportComment.test.js
Labels: Needs Merge

#79 #[16370397] Admin/Moderator should be able to view reported comments and block them.
  src/api/controllers/admin/adminPermissionsController.js
  src/api/controllers/admin/commentReportController.js
  src/api/models/comment.js
  src/api/models/reasons.js
  src/api/routes/adminRouter.js
  src/api/seeders/20190719110459-reportComment.js
  src/helpers/tests/adminSignIn.js
  tests/admin.reported.comment.test.js
Labels: Needs Merge

#80 ft-#167370397 allow admin and moderator to block or unblock reported comments
  src/api/controllers/admin/commentReportController.js
  src/api/migrations/20190718162333-comment-isBlocked.js
  src/api/models/comment.js
  src/api/routes/adminRouter.js
  src/api/seeders/20190718163410-reported-comment.js
  src/docs/swagger.json
  src/middlewares/checkIfCommentExist.js
  src/middlewares/isCommentBlocked.js
  tests/admin.reported.comment.test.js
Labels: Needs Review, Needs approval

#81 166240833 Users should be able to receive notifications
  package.json
  src/api/controllers/articleController.js
  src/api/controllers/authController.js
  src/api/controllers/commentController.js
  src/api/controllers/notificationController.js
  src/api/controllers/password.reset.js
  src/api/controllers/reportCommentController.js
  src/api/migrations/20190708141337-create-stat.js
  src/api/migrations/20190717152603-create-notifications-table.js
  src/api/migrations/20190717153700-create-notifications-config-table.js
  src/api/models/article.js
  src/api/models/comment.js
  src/api/models/index.js
  src/api/models/notification.js
  src/api/models/notificationConfig.js
  src/api/models/report.js
  src/api/models/reportComment.js
  src/api/models/user.js
  src/api/routes/articleRouter.js
  src/api/routes/index.js
  src/api/routes/notificationRouter.js
  src/api/seeders/20190621184055-user.js
  src/api/seeders/20190718104706-test-notification-configs.js
  src/helpers/Mailer/index.js
  src/helpers/Mailer/templates/index.js
  src/helpers/Mailer/templates/notifications.js
  src/helpers/Mailer/templates/passwordResetEmailConfig.js
  src/helpers/constants/default.notification.configs.json
  src/helpers/constants/email.unsubscription.config.json
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  src/helpers/create.default.notifications.config.js
  src/helpers/event.emitter.js
  src/helpers/event.listeners.js
  src/helpers/notifications/block.article.js
  src/helpers/notifications/block.comment.js
  src/helpers/notifications/get.user.config.js
  src/helpers/notifications/report.article.js
  src/helpers/notifications/report.comment.js
  src/helpers/notifications/sender.js
  src/index.js
  src/middlewares/check.update.notification.js
  src/middlewares/register.app.js
  tests/article.comments.js
  tests/notifications.test.js
Labels: Needs approval
