Repository andela/savage_rangers-ah, pull requests merged in 2019-06, with the labels that each got.

#6 [Ch #166240813] deploy base application to heroku
  .hound.yml
  .travis.yml
  Procfile
  index.js
  package.json
  src/index.js
Labels: WIP

#5 #166240815 integrate Coveralls code coverage service
  .coveralls.yml
  .travis.yml
  README.md
  package.json
Labels: WIP

#12 #166501135 removing conflicts and fixing Travis
  .travis.yml
  README.md
  package.json
Labels: Needs Review

#11 #166494346 fix deploy to heroku issue
  .hound.yml
  .travis.yml
  Procfile
  package.json
Labels: Needs Merge

#7 #166240809 Configure Authors to use PostgreSQL as DB Engine
  .env.example
  .gitignore
  .travis.yml
  package.json
  src/api/controllers/db.test.js
  src/api/models/index.js
  src/api/models/test.js
  src/api/routes/db.test.js
  src/api/routes/index.js
  src/index.js
  test/db.test.js
Labels: WIP

#16 #166240818 send the token to the user
  .env.example
  package.json
  src/api/controllers/authController.js
  src/api/controllers/db.test.js
  src/api/models/index.js
  src/api/models/test.js
  src/api/models/token.js
  src/api/models/user.js
  src/api/routes/authRouter.js
  src/api/routes/db.test.js
  src/api/routes/index.js
  src/configs/environments.js
  src/docs/swagger.json
  src/helpers/results/send.auth.js
  src/helpers/tokens/generate.token.js
  src/helpers/tokens/validate.token.js
  src/index.js
  src/middlewares/register.app.js
  test/auth.test.js
  test/db.test.js
  test/default.test.js
  test/home.test.js
Labels: affecting #166240819

#26 #166648563 Fix the travis build failure
  .travis.yml
  src/configs/environments.js
Labels: Done

#20 166240823 Users should be able to reset password via email
  .env.example
  .gitignore
  .travis.yml
  package.json
  src/api/controllers/authController.js
  src/api/controllers/password.reset.js
  src/api/routes/authRouter.js
  src/api/routes/index.js
  src/api/routes/password.reset.js
  src/configs/environments.js
  src/docs/swagger.json
  src/helpers/Mailer/index.js
  src/helpers/Mailer/templates/index.js
  src/helpers/Mailer/templates/notifications.js
  src/helpers/constants/error.messages.js
  src/helpers/constants/validation.schemas.js
  src/helpers/error.sender.js
  src/helpers/tokens/decode.token.js
  src/helpers/tokens/generate.link.js
  src/index.js
  src/middlewares/validations/body.inputs.js
  src/middlewares/validations/body.verifier.js
  src/middlewares/validations/validate.reset.email.js
  src/middlewares/validations/validate.reset.link.js
  src/middlewares/validations/validate.update.password.js
  test/auth.test.js
Labels: Needs Merge, Needs Review

#31 #166730023 Ensure Eslint and Hound-ci are properly setup
  .env.example
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  .gitignore
  package.json
  src/api/controllers/authController.js
  src/api/controllers/home.js
  src/api/controllers/password.reset.js
  src/api/models/index.js
  src/api/models/token.js
  src/api/models/user.js
  src/api/routes/authRouter.js
  src/api/routes/index.js
  src/api/routes/password.reset.js
  src/configs/environments.js
  src/docs/swagger.json
  src/helpers/constants/status.codes.js
  src/middlewares/validations/body.inputs.js
  src/middlewares/validations/body.verifier.js
  src/middlewares/validations/validate.reset.email.js
  src/middlewares/validations/validate.reset.link.js
  src/middlewares/validations/validate.update.password.js
  test/auth.test.js
Labels: Needs Merge

#36 #166800381 Ensure the error objects respect the structure provided in the README
  .eslintrc.js
  .eslintrc.json
  src/api/controllers/authController.js
  src/api/controllers/password.reset.js
  src/api/routes/docs.js
  src/api/routes/password.reset.js
  src/helpers/constants/error.messages.js
  src/helpers/error.sender.js
  src/middlewares/validations/body.inputs.js
  src/middlewares/validations/body.verifier.js
  src/middlewares/validations/validate.reset.email.js
  src/middlewares/validations/validate.reset.link.js
  src/middlewares/validations/validate.update.password.js
  test/auth.test.js
  test/home.test.js
Labels: Needs Merge

#17 [#166240820] Validate signup
  package.json
  src/api/routes/authRouter.js
  src/api/routes/signup.js
  src/configs/environments.js
  src/helpers/tokens/generate.token.js
  src/helpers/validators/signupValidator.js
  src/index.js
  src/middlewares/ValidateUser.js
  src/middlewares/register.app.js
  tests/auth.test.js
  tests/home.test.js
  tests/middlewares/signupValidator.test.js
Labels: Needs Review

#42 #166841614 Configure migrations with the current codebase
  .env.example
  .eslintignore
  .sequelizerc
  .travis.yml
  README.md
  package.json
  src/api/controllers/authController.js
  src/api/controllers/password.reset.js
  src/api/migrations/20190620192200-create-user.js
  src/api/migrations/20190620193548-create-token.js
  src/api/models/index.js
  src/api/models/token.js
  src/api/models/user.js
  src/api/seeders/20190621184055-user.js
  src/configs/environments.js
  src/helpers/Mailer/index.js
  src/helpers/sequelize.initializer.js
  src/helpers/tokens/decode.token.js
  src/helpers/tokens/generate.link.js
  src/helpers/validators/signupValidator.js
  src/index.js
  tests/auth.test.js
  tests/home.test.js
Labels: Needs Merge, Needs approval

#19 [166240824] Enable Social Login via Google and Facebook
  .env.example
  .hound.yml
  package.json
  src/api/controllers/authController.js
  src/api/controllers/socialAuth.js
  src/api/models/user.js
  src/api/routes/authRouter.js
  src/configs/environments.js
  src/configs/passport.js
  src/docs/swagger.json
  src/middlewares/register.app.js
  src/middlewares/social/social.js
  tests/home.test.js
  tests/socialLogin.test.js
Labels: Needs approval

#18 [166240821] Enable the user to sign out of the system
  .gitignore
  .travis.yml
  package.json
  src/api/controllers/authController.js
  src/api/controllers/home.js
  src/api/migrations/20190625141012-create-token-table.js
  src/api/migrations/20190625141140-drop-token-table.js
  src/api/models/index.js
  src/api/models/token.js
  src/api/routes/authRouter.js
  src/api/seeders/20190621184055-user.js
  src/configs/redisConfigs.js
  src/docs/swagger.json
  src/helpers/Blacklist.redis.js
  src/helpers/tokens/generate.token.js
  src/helpers/tokens/getRedisToken.js
  src/middlewares/checkValidToken.js
  tests/auth.test.js
  tests/checkValidToken.test.js
  tests/redis.test.js
  tests/socialLogin.test.js
Labels: Needs Merge

#46 #166240819 enable user email verification
  package.json
  src/api/controllers/authController.js
  src/api/controllers/verifyEmail.js
  src/api/routes/authRouter.js
  src/docs/swagger.json
  src/helpers/constants/error.messages.js
  tests/verify.test.js
Labels: Needs Review
